package com.xwtech.db;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.xwtech.db.PicCache;

import com.xwtech.db.PicCacheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 作者：aaaa

 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig picCacheDaoConfig;

    private final PicCacheDao picCacheDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        picCacheDaoConfig = daoConfigMap.get(PicCacheDao.class).clone();
        picCacheDaoConfig.initIdentityScope(type);

        picCacheDao = new PicCacheDao(picCacheDaoConfig, this);

        registerDao(PicCache.class, picCacheDao);
    }
    
    public void clear() {
        picCacheDaoConfig.getIdentityScope().clear();
    }

    public PicCacheDao getPicCacheDao() {
        return picCacheDao;
    }

}
